/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ButtonPrimary: typeof import('./src/components/shared/ButtonPrimary.vue')['default']
    ButtonSecondary: typeof import('./src/components/shared/ButtonSecondary.vue')['default']
    Feature: typeof import('./src/components/Feature.vue')['default']
    Features: typeof import('./src/components/Features.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    Games: typeof import('./src/components/games.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    Heading1: typeof import('./src/components/shared/Heading1.vue')['default']
    Heading2: typeof import('./src/components/shared/Heading2.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    MsgModal: typeof import('./src/components/msgModal.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RealPop: typeof import('./src/components/payout/realPop.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
